package com.ztcwork.demo.entity; /**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import org.apache.thrift.TEnum;

public enum dcColType implements TEnum {
  Empty(0),
  Object(1),
  DBNull(2),
  Boolean(3),
  Char(4),
  SByte(5),
  Byte(6),
  Int16(7),
  UInt16(8),
  Int32(9),
  UInt32(10),
  Int64(11),
  UInt64(12),
  Single(13),
  Double(14),
  Decimal(15),
  DateTime(16),
  String(18);

  private final int value;

  private dcColType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static dcColType findByValue(int value) { 
    switch (value) {
      case 0:
        return Empty;
      case 1:
        return Object;
      case 2:
        return DBNull;
      case 3:
        return Boolean;
      case 4:
        return Char;
      case 5:
        return SByte;
      case 6:
        return Byte;
      case 7:
        return Int16;
      case 8:
        return UInt16;
      case 9:
        return Int32;
      case 10:
        return UInt32;
      case 11:
        return Int64;
      case 12:
        return UInt64;
      case 13:
        return Single;
      case 14:
        return Double;
      case 15:
        return Decimal;
      case 16:
        return DateTime;
      case 18:
        return String;
      default:
        return null;
    }
  }
}
